spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loans_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuration pour OpenFeign (si utilisé)
# feign:
#   client:
#     config:
#       default:
#         connectTimeout: 5000
#         readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'