spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/public_catalog_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Si vous utilisez Spring Cloud Stream pour la synchronisation
# spring:
#   cloud:
#     stream:
#       kafka:
#         binder:
#           brokers: localhost:9092
#       bindings:
#         input: # Nom du canal d'entrée
#           destination: book-events # Nom du topic Kafka/queue RabbitMQ

management:
  endpoints:
    web:
      exposure:
        include: '*'